name: Desafio4

on: push

jobs:
  pushlish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout recursive
        uses: actions/checkout@v2
      - name: Deploy to desafio4.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'desafio3.surge.sh'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}